# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key-val.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkey-val.proto\x12\x06keyval\"\x12\n\x03Key\x12\x0b\n\x03val\x18\x01 \x01(\t\"#\n\x05Value\x12\x0b\n\x03val\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"F\n\x0cKeyValuePair\x12\x18\n\x03key\x18\x01 \x01(\x0b\x32\x0b.keyval.Key\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.keyval.Value2g\n\x08KeyValue\x12(\n\x08GetValue\x12\x0b.keyval.Key\x1a\r.keyval.Value\"\x00\x12\x31\n\x08SetValue\x12\x14.keyval.KeyValuePair\x1a\r.keyval.Value\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_val_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEY']._serialized_start=25
  _globals['_KEY']._serialized_end=43
  _globals['_VALUE']._serialized_start=45
  _globals['_VALUE']._serialized_end=80
  _globals['_KEYVALUEPAIR']._serialized_start=82
  _globals['_KEYVALUEPAIR']._serialized_end=152
  _globals['_KEYVALUE']._serialized_start=154
  _globals['_KEYVALUE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
